export class Program {
    programId: number;
    masterProgramId: number;
    programTypeId: number;
    copyRulesFrom:number;
    programName: string;
    programModeId: string;
    startDate: string;
    endDate:string;
    totalLimit:DoubleRange;
    limitPerBorrower:DoubleRange;
    minROI:DoubleRange;
    maxROI:DoubleRange;
    interestType:string;
    createdBy:number;
    activeInd:string;
    createdOn:Date;
    partner:Array<any>;
    lenders:Array<any>;
    beneficiary :Array<any>;
    programLimit :Array<any>;
    repayment :Array<any>;
    cashDiscount:Array<any>;
    noOfInstallment:number;
    installmentType:string;
    loanTenure:number;
    loanTenureUnit:string;
    status:number;
    pfTypeId:string;
    noOfTranchesPerDay:number;
    tranchLimitPercentage:number;
    coApplicantSoleProp:number;
    cashDiscountFlag:number;
    cashDiscountType:number;
    cashDiscountValue:number;
    notificationTypeId:number;
    notificationFreqId:number;
    adjustMinPercentage:number;
    adjustMaxPercentage:number;
    programDesc:string;
    loanToSoleProp:number;
    autoDisbursementFlag:number;
    disbursementHoldTime:any;
    migrationAllowed:any;
    lenderTenure:any;
    spTenure:any;
    requiredMonthsBankStatement:any;
    gracePeriod:any;
    overDuePeriod:any;
    orderInvoiceDisbursal:any;
    orderInvoiceDisbursalLimit:any;
    minimumValueofAcceptedInvoice:any;
    dueDateSelection:any;
    borrowerRoiType:any;
    borrowerLoanTenureType:any;
    customConfigList :Array<any>;
    maxFreeCredit:any;
    interestTypeId:number;
    eSigningFlag:any;
    stampPaperFlag:any;
    hypothecationFlag:any;
    loanAgreementFlag:any;
    eStampDutyProcurementFlag: any;
    digitalFlowFlag:number;
    enach: any;
    programConfig: Array<any>;
    smeType:any;
    staleDays:string;
    interestRunType: number;
    breRule:number;
    fldg: number;
    fldgPercentage: number;

}
