export const lenderconfiguration = {

	// lenderName : 'FinAGG Quick Cash Flow™',
	// loginLogo:'assets/images/lender/finagg/finagg-logo-tm.png',
	// loaderUrl:'',
	// lenderLogo:'assets/images/lender/finagg/finagg-logo-tm.png',
    // // lenderLogo:'assets/images/lender/jana/jana-logos.jpeg',
	// lenderMobile : '8186081830',
	// lenderWp : '8920201334',
	// lenderMail : '',
	// favIcon:'assets/images/finagg-logo.png',
	// Name:'FinAgg',
	// env:'Fin',
	// gstpassword:true,
	// lenderFooter:'© FinAGG Technologies Pvt. Ltd. All rights reserved.',
	// spliterKey:'TqKlT',
	// locktime:'5'
	//tvsc
	// lenderName : 'TVS Credit',
	// loginLogo:'assets/images/lender/tvsc/tvsc_logo.png',
	// loaderUrl:'assets/images/lender/tvsc/loading.gif',
	// lenderLogo:'assets/images/lender/tvsc/tvsc_logo.png',
	// lenderMobile : '8186081830',
	// lenderWp : '8920201334',
	// lenderMail : '',
    // favIcon:'assets/images/lender/tvsc/tvsc_logo.png',
	// Name:'TVSC',
	// env:'Tvsc',
	// lenderFooter:'TVS Credit SCF powered by FinAGG Quick Cash Flow™'
	lenderName : 'Jana Small Finance Bank',
	loginLogo:'assets/images/lender/jana/jana-logos.jpeg',
	loaderUrl:'assets/images/lender/jana/jana-logos.jpeg',
	lenderLogo:'assets/images/lender/jana/jana-logos.jpeg',
	lenderMobile : '8186081830',
	lenderWp : '8920201334',
	lenderMail : 'customercare@janabank.com',
    favIcon:'assets/images/jana-logos.jpeg',
	Name:'Jana',
	env:'Jana',
	locktime:'5',
	gstpassword:false,
	lenderFooter:'JSFB SCF powered by FinAGG Quick Cash Flow™',
	spliterKey:'TqKlT',
	//abfl
	// lenderName : 'Aditya Birla Finance Limited ',
	// loginLogo:'assets/images/lender/abfl/abfl_logo.jpg',
	// loaderUrl:'assets/images/lender/abfl/abfl_logo.jpg',
	// lenderLogo:'assets/images/lender/abfl/abfl_logo.jpg',
	// lenderMobile : '8186081830',
	// lenderWp : '8920201334',
	// lenderMail : '',
    // favIcon:'assets/images/abfl_logo.jpeg',
	// Name:'ABFL',
	// env:'Abfl',
	// lenderFooter:'ABFL SCF powered by FinAGG Quick Cash Flow™'
	
}; 