
export const Constant = {
	errorMSG: 'Sorry! We are not able to process your request currently, Please try again. If problem persists, Please contact Tech Support.',
	Merchant_analysis_Call : 61,
	Merchant_analysis_Rule : 62,
	Penny_Drop_API_call : 63,
	Rerun_Brand_Rule : 64,
	Rerun_Bureau_Rule : 65,
	Rerun_Bank_Rule : 66,
	program_selection : 67,
	spliterKey:'TqKlT',
}
export const lender = {
	IDFC:100,
	UGRO:740,
	FINAGG:341
}
export const retailerConstant = {
	retailerProgramTypeId: 1,
	retailerStatusFlow: 1,


	// retailer start
	// status
	DRAFT: 20,
	SUBMITTED_Status: 21,
	SUBMITTED_TO_FI: 22,
	KYC: 23,
	REJECTED_BY_FI: 24,
	LIVE: 26,
	READY_FOR_LIVE: 36,
	REJECTED_BY_FA: 38,
	READY_FOR_DOC: 39,
	Shop_Verification: 40,
	GST_Process: 41,
	NACH: 87,
	Loan_Status: 88,
	retailer_Finagg_Credit_Approval:127,
	retailer_Lender_Credit_Approval:128,
	retailer_Finagg_Ops_Approval:129,
	retailer_Lender_Ops_Approval:130,
	retailer_Review_Limit:144,
	// substatus
	SUBMITTED_SubStatus: 1,
	CANCELLED: 2,
	Telco_Pass: 22,
	Telco_Fail: 23,
	PENDING_AT_CUSTOMER: 3,
	PENDING_AT_FINAGG_USER: 4,
	REJECTED_BY_FINAGG: 5,
	SUBMITTED_TO_FI_Sub: 6,
	PAN_Verification_Pending: 24,
	PAN_Verification_Pass: 25,
	PAN_Verification_Fail: 26,
	REJECTED_BY_FI_Sub: 7,
	RETURN_TO_FINAGG_USER: 8,
	APPROVED: 9,
	Accepted_By_FI: 29,
	Rejected_By_FI: 30,
	Lender_Ops_Verification_Pending: 31,
	Lender_Ops_Verification_Complete: 32,
	Bank_Statement_Pending: 33,
	Bank_Statement_Received: 34,
	Bank_Rule_Pass: 35,
	Bank_Rule_Fail: 36,
	READY_FOR_DOC_Sub: 16,
	READY_FOR_LIVE_Sub: 17,
	KYC_Pending: 27,
	KYC_Complete: 28,
	LIVE_Sub: 18,
	OVERDUE: 19,
	Rejected_By_FA: 39,
	Loan_Doc_Pending: 37,
	Loan_Doc_Completed: 38,
	NACH_Form_Upload_Pending: 143,
	NACH_Form_Upload_Complete: 144,
	NACH_Status_Awaited: 145,
	NACH_Accepted: 146,
	NACH_Rejected: 147,
	Loan_Status_Pending: 150,
	Loan_In_progress_IDFC: 151,
	Loan_Status_Approved: 152,
	Loan_Status_Rejected: 153,

	
	retailer_Finagg_Credit_Approve_reject: 300,
	retailer_Finagg_Credit_Approved: 301,
	retailer_Finagg_Credit_Rejected: 302,
	retailer_Lender_Credit_Approve_reject: 303,
	retailer_Lender_Credit_Approved: 304,
	retailer_Lender_Credit_Rejected: 305,
	retailer_Finagg_Ops_Approve_reject: 306,
	retailer_Finagg_Ops_Approved: 307,
	retailer_Finagg_Ops_Rejected: 308,
	retailer_Lender_Ops_Approve_reject: 309,
	retailer_Lender_Ops_Approved: 310,
	retailer_Lender_Ops_Rejected: 311,
	retailer_Modify_Limit:351,
	retailer_create_loan:348,
	// retailer end 	
};

export const nonSoleProp = {
	nonSoleStatusFlow: 3,
	// status
	OnBoarding: 69,
	Application_Form: 70,
	Loan_Docs_Upload: 71,
	Posidex_Call: 72,
	Create_Loan: 73,
	Loan_Status: 74,
	Loan_Application_And_Agreement: 75,
	NACH: 76,
	Ready_For_Live: 77,
	Application_Rejected: 78,
	Live: 79,
	non_sole_Finagg_Credit_Approval:135,
	non_sole_Lender_Credit_Approval:136,
	non_sole_Finagg_Ops_Approval:137,
	non_sole_Lender_Ops_Approval:138,
	non_sole_Review_Limit_Calculation:146,
	// subStatus
	Telco_Pass: 90,
	Telco_Fail: 91,
	Brand_Rule_Pass: 92,
	Brand_Rule_Fail: 93,
	PAN_Data_upload_Complete: 94,
	Utility_Bill_Data_Collected: 95,
	Bank_Statement_Pending: 96,
	Bank_Statement_Received: 97,
	Bank_Rule_Pass: 98,
	Bank_Rule_Fail: 99,
	Application_Form_Update_Pending: 100,
	Application_Form_Update_Complete: 101,
	Loand_Docs_Uploaded_to_Filenet_Pending: 102,
	Loand_Docs_Uploaded_to_Filenet_Complete: 103,
	Posidex_call_pending: 104,
	Posidex_call_Complete: 105,
	Posidex_call_Failed: 106,
	Create_Loan_Pending: 107,
	Create_Loan_Success: 108,
	Create_Loan_Failure: 109,
	Loan_Status_Pending: 110,
	Loan_Status_Approved: 111,
	Loan_Status_Rejected: 112,
	Loan_Application_and_Agreement_Pending: 113,
	Docs_sent_for_sign_off: 114,
	Signed_docs_uploaded_to_IDFC_Filenet: 115,
	NACH_Form_Upload_Pending: 116,
	NACH_Form_Upload_Complete: 117,
	NACH_Status_Awaited: 118,
	NACH_Accepted: 119,
	NACH_Rejected: 120,
	non_sole_Finagg_Credit_Approve_reject: 324,
	non_sole_Finagg_Credit_Approved: 325,
	non_sole_Finagg_Credit_Rejected: 326,
	non_sole_Lender_Credit_Approve_reject: 327,
	non_sole_Lender_Credit_Approved: 328,
	non_sole_Lender_Credit_Rejected: 329,
	non_sole_Finagg_Ops_Approve_reject: 330,
	non_sole_Finagg_Ops_Approved: 331,
	non_sole_Finagg_Ops_Rejected: 332,
	non_sole_Lender_Ops_Approve_reject: 333,
	non_sole_Lender_Ops_Approved: 334,
	non_sole_Lender_Ops_Rejected: 335,
	non_sole_Modify_Limit:353,
};

export const sellerConstant = {
	finagg_lender_id: 381,
	sellerProgramTypeId: 2,
	sellerStatusFlow: 2,
	//status
	OnBoarding: 53,
	GST_Processing: 54,
	GST_Rule: 55,
	Bank_Processing: 56,
	Loan_Docs_Upload: 57,
	Posidex_Call: 58,
	Commercial_Bureau: 59,
	Commercial_Bureau_rule: 60,
	Loan_Application_And_Agreement: 61,
	NACH: 62,
	Live: 63,
	Ready_for_live: 64,
	Create_Loan: 66,
	Application_Form: 67,
	Loan_Status: 68,
	Fraud_Check : 118,
	Consumer_Bureau : 119,
	Consumer_Bureau_Rule : 120,
	Credit_Approval : 122,
	seller_Finagg_Credit_Approval:131,
	seller_Lender_Credit_Approval:132,
	seller_Finagg_Ops_Approval:133,
	seller_Lender_Ops_Approval:134,
	seller_Review_Limit_Calculation:145,
	//substatus
	SELLER_PAN_UPLOAD: 51,
	SELLER_UTIL_BILL: 52,
	SELLER_GST_DATA_COLLECTED: 53,
	SELLER_BANK_DATA_COLLECTED: 54,

	SELLER_GST_PROCESS_PENDING: 55,
	SELLER_GST_PROCESS_COMPLETE: 80,

	SELLER_GST_RULE_PASS: 56,
	SELLER_GST_RULE_FAIL: 57,

	SELLER_BANK_PROCESS_PENDING: 58,
	SELLER_BANK_RULE_PASS: 59,
	SELLER_BANK_RULE_FAIL: 60,

	SELLER_APPLICATION_FORM_PENDING: 85,
	SELLER_APPLICATION_FORM_COMPLETE: 86,

	SELLER_POSIDEX_PENDING: 64,
	SELLER_POSIDEX_COMPLETE: 65,
	SELLER_POSIDEX_FAIL: 74,

	SELLER_DOC_FILENET_PENDING: 62,
	SELLER_DOC_FILENET_COMPLETE: 63,

	SELLER_COMMERCIAL_BUREAU_PENDING: 66,
	SELLER_COMMERCIAL_BUREAU_REQEUST: 67,
	SELLER_COMMERCIAL_BUREAU_RES_RECEIVED: 81,
	SELLER_COMMERCIAL_BUREAU_RES_FAILED: 142,

	SELLER_Commercial_BUREAU_RULE_PASS: 68,
	SELLER_Commercial_BUREAU_RULE_FAIL: 69,

	SELLER_CREATE_LOAN_PENDING: 84,
	SELLER_CREATE_LOAN_SUCCESS: 82,
	SELLER_CREATE_LOAN_FAIL: 83,

	SELLER_LOAN_STATUS_PENDING: 87,
	SELLER_LOAN_STATUS_APPROVED: 88,
	SELLER_LOAN_STATUS_REJECTED: 89,

	SELLER_LOAN_DOCS_PENDING: 70,
	SELLER_LOAN_DOCS_SIGNOFF: 71,
	SELLER_LOAN_DOCS_IDFC: 72,

	SELLER_NACH_UPLOAD_PENDING: 75,
	SELLER_NACH_UPLOAD_COMPLETE: 76,
	SELLER_NACH_STATUS_AWAITED: 77,
	SELLER_NACH_ACCEPTED: 78,
	SELLER_NACH_REJECTED: 79,
	SELLER_Draft_Application_Form: 157,
	
	SELLER_Fraud_CALL_Initiated : 273,
	SELLER_Fraud_CALL_Completed : 274,
	SELLER_Fraud_CALL_Accepted	 : 275,
	SELLER_Fraud_CALL_Rejected	:276,
	SELLER_Fraud_CALL_NO_Response: 277,

	SELLER_Consumer_Bureau_CALL_Initiated:278,
	SELLER_Consumer_Bureau_CALL_Request_Completed:279,
	SELLER_Consumer_Bureau_CALL_NO_Response: 280,
	
	SELLER_Consumer_Bureau_rule_fail: 281,
	SELLER_Consumer_Bureau_rule_pass: 282,

	SELLER_ApproveReject: 285,
	SELLER_Approved: 286,
	SELLER_Rejected: 287,

	seller_Finagg_Credit_Approve_reject: 312,
	seller_Finagg_Credit_Approved: 313,
	seller_Finagg_Credit_Rejected: 314,
	seller_Lender_Credit_Approve_reject: 315,
	seller_Lender_Credit_Approved: 316,
	seller_Lender_Credit_Rejected: 317,
	seller_Finagg_Ops_Approve_reject: 318,
	seller_Finagg_Ops_Approved: 319,
	seller_Finagg_Ops_Rejected: 320,
	seller_Lender_Ops_Approve_reject: 321,
	seller_Lender_Ops_Approved: 322,
	seller_Lender_Ops_Rejected: 323,
	SELLER_Modify_Limit:352,
};
export const disbursalConstant = {
	// statusId
	In_Progress: 1,
	Approved: 2,
	Rejected: 3,
	// substatus
	Disbursement_Initiated: 40,
	installment_schedule_Accepted: 4,
	eNach_Completed: 42,
	DRF_Completed: 43,
	Drawdown_request_placed_with_lender: 44,
	eNach_Failure: 48,
	OTP_Completed: 159,
	Disbursement_Pending: 160,
	Money_received_in_escrow: 45,
	Disbursement_to_beneficiary_initiated: 46,
	Disbursement_to_beneficiary_completed: 47,
	Drawdown_request_placement_failed: 49,
	Disbursement_to_beneficiary_failed: 50,
	Disbursement_Approved: 161,
	Disbursement_Rejected: 162,
};
export const gemConstant = {
	gemProgramTypeId: 3,
	gemStatusFlow: 4,

	// StatusConstant
	SUCCESS: "SUCCESS",
	FAILURE: "FAILURE",
	ACTIVE: "ACTIVE",

	// LoanApplicationStatus
	PROCESSING: "PROCESSING",
	OFFERED: "OFFERED",
	OFFER_ACCEPTED: "OFFER_ACCEPTED",
	GRANTED: "GRANTED",
	REJECTED: "REJECTED",
	ACTION_REQUIRED: "ACTION_REQUIRED",

	// Status
	KYC: 87,
	CREATE_LOAN: 80,
	GENERATE_OFFER: 81,
	SET_OFFER: 82,
	LOAN_ACCEPTANCE: 83,
	VERIFY_LOAN_ACCEPTANCE: 84,
	PROCESS_DISBURESEMENT: 86,
	SET_DISBURESEMENT_ACCOUNT: 88,
	GRANT_LOAN: 85,

	// SubStatus
	KYC_PENDING: 142,
	KYC_SUCCESS: 143,
	KYC_FAILED: 144,

	CREATE_LOAN_PENDING: 121,
	CREATE_LOAN_SUCCESS: 122,
	CREATE_LOAN_FAILED: 123,

	GENERATE_OFFER_PENDING: 124,
	GENERATE_OFFER_SUCCESS: 125,
	GENERATE_OFFER_FAILED: 126,

	SET_OFFER_PENDING: 127,
	SET_OFFER_SUCCESS: 128,
	SET_OFFER_FAILED: 129,

	LOAN_ACCEPTANCE_PENDING: 130,
	LOAN_ACCEPTANCE_SUCCESS: 131,
	LOAN_ACCEPTANCE_FAILED: 132,

	LOAN_VERIFICATION_PENDING: 133,
	LOAN_VERIFICATION_SUCCESS: 134,
	LOAN_VERIFICATION_FAILED: 135,

	PROCESS_DISBURESEMENT_PENDING: 139,
	PROCESS_DISBURESEMENT_SUCCESS: 140,
	PROCESS_DISBURESEMENT_FAILED: 141,

	SET_DISBURESEMENT_ACCOUNT_PENDING: 145,
	SET_DISBURESEMENT_ACCOUNT_SUCCESS: 146,
	SET_DISBURESEMENT_ACCOUNT_FAILED: 147,

	GRANTLOAN_PENDING: 136,
	GRANTLOAN_SUCCESS: 137,
	GRANTLOAN_FAILED: 138,
};

export const dealerConstant = {
	DEALERProgramTypeId: 4,
	DEALERStatusFlow: 5,
	//status
	// OnBoarding: 104,
	// GST_Processing: 105,
	// GST_Rule:106,
	// Bank_Processing: 117,
	// Loan_Docs_Upload: 110,
	// Posidex_Call: 107,
	// Commercial_Bureau: 109,
	// Bureau_rule: 108,
	// Loan_Application_And_Agreement: 112,
	// NACH: 113,
	// Live: 116,
	// Ready_for_live: 115,
	// Create_Loan: 111,
	// Application_Form: 235,
	// Loan_Status: 114,
	Dealer_OnBoarding: 89,
	Dealer_GST_Processing: 90,
	Dealer_GST_Rule: 91,
	Dealer_Posidex_Call: 92,
	Dealer_Commercial_Bureau: 93,
	Dealer_Bureau_Rule: 94,
	Dealer_Loan_Doc_Upload: 95,
	Dealer_Create_Loan: 96,
	Dealer_Loan_Application_And_Agreement: 97,
	Dealer_Nach: 98,
	Dealer_Loan_Status: 99,
	Dealer_Ready_for_Live: 100,
	Dealer_Live: 101,
	Dealer_Bank_Processing: 102,
	Dealer_Appilcation_Form: 103,
	Dealer_POSIDEX_LOAN_REJECTED: 104,

	Dealer_Finagg_Credit_Approval:139,
	Dealer_Lender_Credit_Approval:140,
	Dealer_Finagg_Ops_Approval:141,
	Dealer_Lender_Ops_Approval:142,
	Dealer_Review_Limit_Calculation:147,
	Dealer_Fraud_check:149,
	Dealer_Consumer_Bureau:150,
	Dealer_Consumer_Bureau_Rule:151,
	Dealer_Nach_PDC:152,
	Dealer_PDC:153,
	Dealer_Financial_CHECK:154,
	Dealer_Aadhaar_Vault_API_Call:169,
	Dealer_AML_API_Call:170,
	Dealer_AML_Manual_Verify:171,
	Dealer_Dedupe_Call:172,
	Dealer_Dedupe_Manual_Verify:173,
	Dealer_CRN_API_Call:174,
	Dealer_PD:175,
	Dealer_Doc_Verification: 176,
	Dealer_Bre_api_call: 177,

	//substatus
	Dealer_Telco_Pass: 163,
	Dealer_Telco_Fail: 164,
	Dealer_Brand_Pass: 165,
	Dealer_Brand_Fail: 166,
	Dealer_Pan_Data_Uploaded: 167,
	Dealer_Id_Proof_Collected: 168,
	Dealer_Utill_Bill_Collected: 169,
	Dealer_GST_Data_Collected: 170,
	Dealer_Bank_Statement_Pending: 171,
	Dealer_Bank_Statement_Received: 172,
	Dealer_Bank_Proceesing_Pending: 207,
	Dealer_Bank_Rule_Pass: 173,
	Dealer_Bank_Rule_Fail: 174,
	Dealer_GST_Proceesing_Pending: 175,
	Dealer_GST_Proceesing_Complete: 176,
	Dealer_GST_Data_Proceesing_Complete: 177,
	Dealer_GST_Rule_Pass: 178,
	Dealer_GST_Rule_Fail: 179,
	Dealer_Posidex_Pending: 180,
	Dealer_Posidex_Complete: 181,
	Dealer_Posidex_Fail: 182,
	Dealer_Commercial_Bureau_Pending: 183,
	Dealer_Commercial_Bureau_Request_Complete: 184,
	Dealer_Commercial_Bureau_Reponse_Received: 185,
	Dealer_Commercial_Bureau_Reponse_Failed: 186,
	Dealer_Bureau_Rule_Pass: 187,
	Dealer_Bureau_Rule_Fail: 188,
	Dealer_Loan_Docs_Filenet_Pending: 189,
	Dealer_Loan_Docs_Filenet_Complete: 190,
	Dealer_Create_Loan_Pending: 191,
	Dealer_Create_Loan_Success: 192,
	Dealer_Create_Loan_Failure: 193,
	Dealer_Loan_Appl_Pending: 194,
	Dealer_Loan_Appl_Signoff: 195,
	Dealer_Loan_Appl_Sign_Docs_IDFC: 196,
	Dealer_Nach_Form_Upload_Pending: 197,
	Dealer_Nach_Form_Upload_Complete: 198,
	Dealer_Sdfc_Call_Pending:633,
	Dealer_Sdfc_Call_NoResponse:635,
	Dealer_Va_Call_Pending:636,
	Dealer_Va_Call_NoResponse:638,
	Dealer_Nach_Status_Awaited: 199,
	Dealer_Nach_Accepted: 200,
	Dealer_Nach_Rejected: 201,
	Dealer_Loan_Status_Pending: 202,
	Dealer_Loan_InProgress_IDFC: 203,
	Dealer_Loan_Status_Approved: 204,
	Dealer_Loan_Status_Rejected: 205,
	Dealer_App_Form_Update_Pending: 208,
	Dealer_App_Form_Update_Complete: 209,
	Dealer_Draft_App_Form: 210,
	Dealer_Utill_Bill_Pending: 211,
	DEALER_PAN_UPLOAD: 208,
	DEALER_UTIL_BILL: 210,
	DEALER_GST_DATA_COLLECTED: 211,
	DEALER_BANK_DATA_COLLECTED: 213,
    DEALER_SFDC_CALL:250,
	DEALER_VA_CALL:251,
	DEALER_GST_PROCESS_PENDING: 175,
	DEALER_GST_PROCESS_COMPLETE: 176,

	DEALER_GST_RULE_PASS: 219,
	DEALER_GST_RULE_FAIL: 220,

	DEALER_BANK_PROCESS_PENDING: 248,
	DEALER_BANK_RULE_PASS: 214,
	DEALER_BANK_RULE_FAIL: 215,

	DEALER_APPLICATION_FORM_PENDING: 208,
	// DEALER_APPLICATION_FORM_COMPLETE : 235,

	DEALER_POSIDEX_PENDING: 221,
	DEALER_POSIDEX_COMPLETE: 222,
	DEALER_POSIDEX_FAIL: 223,

	DEALER_DOC_FILENET_PENDING: 230,
	DEALER_DOC_FILENET_COMPLETE: 231,

	DEALER_COMMERCIAL_BUREAU_PENDING: 226,
	DEALER_COMMERCIAL_BUREAU_REQEUST: 227,
	DEALER_COMMERCIAL_BUREAU_RES_RECEIVED: 228,
	DEALER_COMMERCIAL_BUREAU_RES_FAILED: 229,

	DEALER_BUREAU_RULE_PASS: 224,
	DEALER_BUREAU_RULE_FAIL: 225,

	DEALER_CREATE_LOAN_PENDING: 232,
	DEALER_CREATE_LOAN_SUCCESS: 233,
	DEALER_CREATE_LOAN_FAIL: 234,

	DEALER_LOAN_STATUS_PENDING: 242,
	DEALER_LOAN_STATUS_APPROVED: 245,
	DEALER_LOAN_STATUS_REJECTED: 246,

	DEALER_LOAN_DOCS_PENDING: 235,
	DEALER_LOAN_DOCS_SIGNOFF: 236,
	DEALER_LOAN_DOCS_IDFC: 237,

	DEALER_NACH_UPLOAD_PENDING: 238,
	DEALER_NACH_UPLOAD_COMPLETE: 239,
	DEALER_NACH_STATUS_AWAITED: 240,
	DEALER_NACH_ACCEPTED: 241,
	DEALER_NACH_REJECTED: 242,
	DEALER_Draft_Application_Form: 210,

	DEALER_Finagg_Credit_Approve_reject: 336,
	DEALER_Finagg_Credit_Approved: 337,
	DEALER_Finagg_Credit_Rejected: 338,
	DEALER_Lender_Credit_Approve_reject: 339,
	DEALER_Lender_Credit_Approved: 340,
	DEALER_Lender_Credit_Rejected: 341,
	DEALER_Finagg_Ops_Approve_reject: 342,
	DEALER_Finagg_Ops_Approved: 343,
	DEALER_Finagg_Ops_Rejected: 344,
	DEALER_Lender_Ops_Approve_reject: 345,
	DEALER_Lender_Ops_Approved: 346,
	DEALER_Lender_Ops_Rejected: 347,
	Dealer_Modify_Limit:354,

	Dealer_Fraud_CALL_Initiated:356,
	Dealer_Fraud_CALL_Completed:357,
	Dealer_Fraud_CALL_Accepted:358,
	Dealer_Consumer_Bureau_CALL_Initiated:359,
	Dealer_Consumer_Bureau_Request_Completed:360,
	Dealer_Consumer_Bureau_NO_Response:361,
	Dealer_Consumer_Bureau_Rule_Pass:362,
	Dealer_Consumer_Bureau_Rule_Fail:363,
	Dealer_NACH_PDC_Pending:365,
	Dealer_PDC_Pending:366,
	Dealer_PDC_Complete:367,
	Dealer_Financial_CALL_Initiated:368,
	Dealer_Financial_CALL_Completed:369,
	Dealer_Financial_CALL_NO_Response:370,

	
	Dealer_Aadhaar_Vault_API_Call_Pending:410,
	Dealer_Aadhaar_Vault_API_Call_complete:411,
	Dealer_Aadhaar_Vault_API_Call_Failled:412,
	Dealer_AML_API_Call_Pending:413,
	Dealer_AML_API_Call_Complete:414,
	Dealer_AML_API_Call_Failled:415,
	Dealer_AML_Manual_Verify_Pending:416,
	Dealer_AML_Accepted:417,
	Dealer_AML_Rejected:418,
	Dealer_Dedupe_Call_Pending:419,
	Dealer_Dedupe_Call_Complete:420,
	Dealer_Dedupe_Call_Failled:421,
	Dealer_Dedupe_Manual_Verify_Pending:422,
	Dealer_Dedupe_Accepted:423,
	Dealer_Dedupe_Rejected:424,
	Dealer_CRN_API_Call_Pending:425,
	Dealer_CRN_API_Call_Complete:426,
	Dealer_CRN_API_Call_Failled:427,
	Dealer_PD_Pending:428,
	Dealer_PD_complete:429,
	Dealer_PD_Accept:430,
	Dealer_PD_Reject:431,
	Dealer_Doc_Verification_Pending:432,
	Dealer_Doc_Verification_Complete:433,
	Dealer_Bre_api_call_pending: 434,
	Dealer_Bre_api_call_complete: 435,
	Dealer_Bre_api_call_failed: 436,
	Dealer_internal_sanction_condition_pending:727
};

export const ugroConstant = {
	UGRO_ProgramTypeId: 5,
	UGRO_StatusFlow: 6,
	//   status
	UGRO_OnBoarding_Stage_1: 105,
	UGRO_Financial_Check: 106,
	UGRO_DeDupe_Call: 107,
	UGRO_Fraud_Check: 108,
	UGRO_Consumer_Bureau: 109,
	UGRO_Consumer_Bureau_rule: 110,
	UGRO_Commercial_Bureau: 111,
	UGRO_Commercial_Bureau_rule: 112,
	UGRO_OnBoarding_Stage_2: 113,
	UGRO_GST_Processing: 114,
	UGRO_GST_Rule: 115,
	UGRO_Bank_Processing: 116,
	UGRO_Application_Form: 117,
	UGRO_Create_Loan: 118,
	UGRO_Loan_Application_And_Agreement: 119,
	UGRO_NACH: 120,
	UGRO_Loan_Status: 121,
	// substatus

	UGRO_PAN_Data_upload_Complete: 212,
	UGRO_ID_Proofs_Collected: 213,
	UGRO_Financial_Statements_Collected: 214,
	UGRO_Draft_Application_Form: 215,

	UGRO_Financial_Call_Pending: 216,
	UGRO_Financial_Call_Pass: 217,
	UGRO_Financial_Call_Succcess: 218,
	UGRO_Financial_Call_Fail: 219,

	UGRO_DeDupe_Call_pending: 220,
	UGRO_DeDupe_Call_complete: 265,
	UGRO_DeDupe_Pass: 221,
	UGRO_DeDupe_Fail: 222,

	UGRO_Fraud_Call_Pending: 223,
	UGRO_Fraud_Call_Success: 266,
	UGRO_Fraud_Call_Pass: 224,
	UGRO_Fraud_Call_Fail: 225,

	UGRO_Consumer_Bureau_Call_Pending: 226,
	UGRO_Consumer_Bureau_Request_Complete: 227,
	UGRO_Consumer_Bureau_Response_Failed: 228,

	UGRO_Consumer_Bureau_rule_pass: 229,
	UGRO_Consumer_Bureau_rule_fail: 230,

	UGRO_Commercial_Bureau_Call_Pending: 231,
	UGRO_Commercial_Bureau_Request_Complete: 232,
	UGRO_Commercial_Bureau_Response_Failed: 233,

	UGRO_Bureau_rule_pass: 234,
	UGRO_Bureau_rule_fail: 235,

	UGRO_Utility_Bill_Data_Pending: 236,
	UGRO_Utility_Bill_Data_Collected: 237,
	UGRO_Bank_Data_Collected: 238,

	UGRO_GST_Processing_Pending: 239,
	UGRO_GST_Processing_Complete: 240,
	UGRO_GST_Processing_Failed: 241,

	UGRO_GST_Rule_Pass: 242,
	UGRO_GST_Rule_Fail: 243,

	UGRO_Bank_Processing_Pending: 244,
	UGRO_Bank_Processing_Recived: 245,
	UGRO_Bank_Processing_Failed: 246,
	UGRO_Bank_Rule_Pass: 247,
	UGRO_Bank_Rule_Fail: 248,

	UGRO_Application_Form_Update_Pending: 249,
	UGRO_Application_Form_Update_Complete: 250,
	UGRO_Application_Form_Update_Failed: 251,

	UGRO_Create_Loan_Pending: 252,
	UGRO_Create_Loan_Complete: 253,
	UGRO_Create_Loan_Failed: 254,

	UGRO_Loan_Application_and_Agreement_Pending: 255,
	UGRO_Docs_sent_for_sign_off: 256,

	UGRO_NACH_Form_Upload_Pending: 257,
	UGRO_NACH_Form_Upload_Complete: 258,
	UGRO_NACH_Status_Awaited: 259,
	UGRO_NACH_Accepted: 260,
	UGRO_NACH_Rejected: 261,

	UGRO_Loan_Status_Pending: 262,
	UGRO_Loan_is_Live: 263,
	
};
export const action = {
	Draft_Application_Form: 81,
	Call_Financial_Check_API: 82,
	Call_DeDupe_API: 83,
	Download_CAM: 84,
	Call_Fraud_Check_API: 85,
	Call_Cosumer_Bureau_Check_API: 86,
	Call_Commercial_Bureau_Check_API: 87,
	Run_GSTN_Rule: 88,
	Bank_Statement_Processing: 89,
	Reset_Bank_Statement_Processing: 90,
	Application_Form: 91,
	Call_Create_Loan_API: 92,
	Loan_Form_Agreement_Form: 93,
	Nach_Download: 94,
	Rejected_FA: 95,
	Telco_Pass: 96,
	Upload_Pan: 97,
	ReUploadPan: 98,
	Update_KYC: 99,
	Lender_Ops_verification: 100,
	Run_Bank_Rule: 101,
	Upload_Filenet: 102,
	Posidex_call: 103,
	Check_Loan_Status: 104,
	Check_Nach_Status: 105,
	NACH_Form_Upload: 106,
	Edit_Application_Form: 107,
	Run_Bureau_Rule: 108,
	GSTN_Processing_Status: 109,
	Re_Run_GSTN_Rule: 110,
	Re_Run_Bureau_Rule: 111,
	Re_Run_Bank_Rule: 112,
	Accept_Dedupe: 113,
	Reject_Dedupe: 114,
	Accept_Fraud_Check: 115,
	Reject_Fraud_Check: 116,
	PD_Pending: 117,
	Update_Final_Limit: 118,
	Run_Financial_Rule: 119,
	Run_Consumer_Rule: 120,
	Run_Commercial_Rule: 121,
};

export const UGROLendor = {

	UgroStatueFlow: 9,
	UgroProgramTypeId: 8,

	// //status id
	Ugro_Lendor_OnBoarding: 105,
	Ugro_Lendor_Pan_Verification: 106,
	Ugro_Lendor_KYC: 107,
	Ugro_Lendor_Consumer_Bureau: 108,
	Ugro_Lendor_Bank_Process: 109,
	Ugro_Lendor_NACH_PDC: 110,
	Ugro_Lendor_NACH: 111,
	Ugro_Lendor_PDC: 112,
	Ugro_Create_Loan:116,
	Ugro_Loan_Application_And_Agreement:117,
	Ugro_Loan_execution:118,
	Ugro_Lendor_Loan_Status: 113,
	Ugro_First_Credit_Approval: 123,
	Ugro_FCU_Approval:124,
	Ugro_Second_Credit_Approval:125,
	Ugro_Business_Approval:126,
	Ugro_Review_Limit_Calculation:147,
	// //substatus id
	Ugro_Lendor_Telco_Rule_Pass: 212,
	Ugro_Lendor_Telco_Rule_Fail: 213,
	Ugro_Lendor_Brand_Rule_Pass: 214,
	Ugro_Lendor_Brand_Rule_Fail: 215,
	Ugro_Lendor_PAN_Verification_Pending: 216,
	Ugro_Lendor_PAN_Verification_Pass: 217,
	Ugro_Lendor_PAN_Verification_Fail: 218,
	Ugro_Lendor_KYC_Pending: 219,
	Ugro_Lendor_KYC_Complete: 220,
	Ugro_Lendor_Consumer_Bureau_Pending: 221,
	Ugro_Lendor_Consumer_Bureau_Complete: 222,
	Ugro_Lendor_Consumer_Bureau_No_Response: 235,
	Ugro_Lendor_Consumer_Bureau_Rule_Pass: 223,
	Ugro_Lendor_Consumer_Bureau_Rule_Fail: 224,
	Ugro_Lendor_Bank_Process_Pending: 225,
	Ugro_Lendor_Bank_Process_Complete: 226,
	Ugro_Lendor_Bank_Rule_Pass: 227,
	Ugro_Lendor_Bank_Rule_Fail: 228,
	Ugro_Lendor_NACHPDC_Pending: 229,
	Ugro_Lendor_NACH_Pending: 230,
	Ugro_Lendor_NACH_Complete: 231,
	Ugro_Lendor_PDC_Pending: 232,
	Ugro_Lendor_PDC_Complete: 233,
	Ugro_Lendor_Create_Loan_Pending: 238,
	Ugro_Lendor_Create_Loan_Complete: 239,
	Ugro_Lendor_Create_Loan_Failure: 240,
	Ugro_Loan_execution_Pending:241,
	Ugro_Loan_execution_Complete:242,
	Ugro_Loan_Application_and_Agreement_Pending:243,
	Ugro_Lendor_Loan_Live: 234,
	Ugro_Fist_Credit_Approve_reject: 288,
	Ugro_Fist_Credit_Approved: 289,
	Ugro_Fist_Credit_Rejected: 290,
	Ugro_FCU_Approve_reject: 291,
	Ugro_FCU_Approved: 292,
	Ugro_FCU_Rejected: 293,
	Ugro_Second_Credit_Approve_reject: 294,
	Ugro_Second_Credit_Approved: 295,
	Ugro_Second_Credit_Rejected: 296,
	Ugro_Business_Approve_reject: 297,
	Ugro_Business_Approved: 298,
	Ugro_Business_Rejected: 299,
	Ugro_Modify_Limit:355,
	
};

export const vendorConstant = {
	VendorProgramTypeId: 6,
	VendorStatusFlow: 7,
	Vendor_OnBoarding: 177,
	Vendor_GST_Processing: 178,
	Vendor_GST_Rule: 179,
	Vendor_Posidex_Call: 180,
	Vendor_Commercial_Bureau: 181,
	Vendor_Bureau_Rule: 182,
	Vendor_Loan_Doc_Upload: 183,
	Vendor_Create_Loan: 184,
	Vendor_Loan_Application_And_Agreement: 185,
	Vendor_Nach: 186,
	Vendor_Loan_Status: 187,
	Vendor_Ready_for_Live: 188,
	Vendor_Live: 189,
	Vendor_Bank_Processing: 190,
	Vendor_Appilcation_Form: 191,
	Vendor_POSIDEX_LOAN_REJECTED: 192,
	Vendor_Finagg_Credit_Approval:193,
	Vendor_Lender_Credit_Approval:194,
	Vendor_Finagg_Ops_Approval:195,
	Vendor_Lender_Ops_Approval:196,
	Vendor_Review_Limit_Calculation:197,
	Vendor_Fraud_check:198,
	Vendor_Consumer_Bureau:199,
	Vendor_Consumer_Bureau_Rule:200,
	Vendor_Nach_PDC:201,
	Vendor_PDC:202,
	Vendor_Financial_CHECK:203,
	Vendor_Aadhaar_Vault_API_Call:204,
	Vendor_AML_API_Call:205,
	Vendor_AML_Manual_Verify:206,
	Vendor_Dedupe_Call:207,
	Vendor_Dedupe_Manual_Verify:208,
	Vendor_CRN_API_Call:209,
	Vendor_PD:210,
	Vendor_Doc_Verification: 211,
	Vendor_Bre_api_call: 177,

	//substatus
	Vendor_Telco_Pass:434,
	Vendor_Telco_Fail:435,
	Vendor_Brand_Rule_Pass:436,
	Vendor_Brand_Rule_Fail:437,
	Vendor_PAN_Data_upload_Complete:438,
	Vendor_ID_Proofs_Collected:439,
	Vendor_Utility_Bill_Data_Collected:440,
	Vendor_GST_Data_Collected:441,
	Vendor_Bank_Statement_Pending:442,
	Vendor_Bank_Statement_Received:443,
	Vendor_Draft_Application_Form:444,
	Vendor_Utill_Bill_Pending:445,
	Vendor_GST_Processing_Pending:446,
	Vendor_GST_Processing_Complete:447,
	Vendor_GST_Data_Processing_Completed:448,
	Vendor_GST_Rule_Pass:449,
	Vendor_GST_Rule_Fail:450,
	Vendor_Posidex_call_pending:451,
	Vendor_Posidex_call_Complete:452,
	Vendor_Posidex_call_Failed:453,
	Vendor_Commercial_Bureau_Call_Pending:454,
	Vendor_Commercial_Bureau_Request_Complete:455,
	Vendor_Commercial_Bureau_Response_Received:456,
	Vendor_Commercial_Bureau_Response_Failed:457,
	Vendor_Bureau_rule_pass:458,
	Vendor_Bureau_rule_fail:459,
	Vendor_Loan_Docs_Uploaded_to_Filenet_Pending:460,
	Vendor_Loan_Docs_Uploaded_to_Filenet_Complete:461,
	Vendor_Create_Loan_Pending:462,
	Vendor_Create_Loan_Success:463,
	Vendor_Create_Loan_Failure:464,
	Vendor_Loan_Application_and_Agreement_Pending:465,
	Vendor_Docs_sent_for_sign_off:466,
	Vendor_Signed_docs_Sent_to_IDFC:467,
	Vendor_NACH_Form_Upload_Pending:468,
	Vendor_NACH_Form_Upload_Complete:469,
	Vendor_NACH_Status_Awaited:470,
	Vendor_NACH_Accepted:471,
	Vendor_NACH_Rejected:472,
	Vendor_Loan_Status_Pending:473,
	Vendor_Loan_In_progress_IDFC:474,
	Vendor_Loan_Status_Approved:475,
	Vendor_Loan_Status_Rejected:476,
	Vendor_Loan_Disbursed:477,
	Vendor_Over_Due:478,
	Vendor_NPA:479,
	Vendor_Bank_Rule_Pass:480,
	Vendor_Bank_Rule_Fail:481,
	Vendor_Bank_Process_Pending:482,
	Vendor_Sdfc_Call_Pending:639,
	Vendor_Sdfc_Call_NoResponse:641,
	Vendor_Va_Call_Pending:642,
	Vendor_Va_Call_NoResponse:644,
	Vendor_Application_Form_Update_Pending:484,
	Vendor_Application_Form_UpdateComplete:485,
	Vendor_Finagg_credit_Approve_Reject:486,
	Vendor_Finagg_credit_Approved:487,
	Vendor_Finagg_credit_Rejected:488,
	Vendor_Lender_Credit_Approve_Reject:489,
	Vendor_Lender_Credit_Approved:490,
	Vendor_Lender_Credit_Rejected:491,
	Vendor_Finagg_Ops_Approve_Reject:492,
	Vendor_Finagg_Ops_Approved:493,
	Vendor_Finagg_Ops_Rejected:494,
	Vendor_Lender_Ops_Approve_Reject:495,
	Vendor_Lender_Ops_Approved:496,
	Vendor_Lender_Ops_Rejected:497,
	Vendor_Modify_Limit:498,
	Vendor_Fraud_CALL_Initiated:499,
	Vendor_Fraud_CALL_Completed:500,
	Vendor_Fraud_CALL_Accepted:501,
	Vendor_Consumer_Bureau_CALL_Initiated:502,
	Vendor_Consumer_Bureau_Request_Completed:503,
	Vendor_Consumer_Bureau_NO_Response:504,
	Vendor_Consumer_Bureau_Rule_Pass:505,
	Vendor_Consumer_Bureau_Rule_Fail:506,
	Vendor_NACH_PDC_Pending:507,
	Vendor_PDC_Pending:508,
	Vendor_PDC_Complete:509,
	Vendor_Financial_CALL_Initiated:510,
	Vendor_Financial_CALL_Completed:511,
	Vendor_Financial_CALL_NO_Response:512,
	Vendor_Financial_Rule_Pass:513,
	Vendor_Financial_Rule_Fail:514,
	Vendor_Aadhaar_Vault_API_Call_Pending:515,
	Vendor_Aadhaar_Vault_API_Call_complete:516,
	Vendor_Aadhaar_Vault_API_Call_Failled:517,
	Vendor_AML_API_Call_Pending:518,
	Vendor_AML_API_Call_Complete:519,
	Vendor_AML_API_Call_Failled:520,
	Vendor_AML_Manual_Verify_Pending:521,
	Vendor_AML_Accepted:522,
	Vendor_AML_Rejected:523,
	Vendor_Dedupe_Call_Pending:524,
	Vendor_Dedupe_Call_Complete:525,
	Vendor_Dedupe_Call_Failled:526,
	Vendor_Dedupe_Manual_Verify_Pending:527,
	Vendor_Dedupe_Accepted:528,
	Vendor_Dedupe_Rejected:529,
	VENDOR_SFDC_CALL:252,
	VENDOR_VA_CALL:253,
	Vendor_CRN_API_Call_Pending:530,
	Vendor_CRN_API_Call_Complete:531,
	Vendor_CRN_API_Call_Failled:532,
	Vendor_PD_Pending:533,
	Vendor_PD_complete:534,
	Vendor_PD_Accept:535,
	Vendor_PD_Reject:536,
	Vendor_Doc_Verification_Pending:537,
	Vendor_Doc_Verification_Complete:538,
	Vendor_skip_bank_statement:483,
	Vendor_internal_sanction_condition_pending:730

};